Numpy Stands for numerical python. Powerful python lybrary that is widely used for scientific computing, data analysis, and numerical computing task.
pip install NumPy

In [5]:
import numpy as np
list1 = [10,20,30,40,50,60]
array1 = np.array(list1, dtype=int)
print(array1)


[10 20 30 40 50 60]


numpy.ndarray

In [6]:
import numpy as np
list1 = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
arr1 = np.array(list1, dtype=int)
print(arr1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [7]:
import numpy as np
arr1 = np.arange(1,9) #arange means array range
print(arr1)

[1 2 3 4 5 6 7 8]


In [8]:
import numpy as np
arr1 = np.arange(11,20).reshape(3,3) # reshape means giving matrix of row * col
print(arr1)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [11]:
import numpy as np
arr1 = np.zeros((3,2), dtype=int)
print(arr1)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
import numpy as np
arr1 = np.ones(45)