Numpy Stands for numerical python. Powerful python lybrary that is widely used for scientific computing, data analysis, and numerical computing task.
pip install NumPy

In [5]:
import numpy as np
list1 = [10,20,30,40,50,60]
array1 = np.array(list1, dtype=int)
print(array1)


[10 20 30 40 50 60]


numpy.ndarray

In [6]:
import numpy as np
list1 = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
arr1 = np.array(list1, dtype=int)
print(arr1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
